---
- hosts: 127.0.0.1
  tasks:

  - name: Install prerequisites
    apt:
      deb: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

  - name: Add universe repository
    command: sudo add-apt-repository universe

  - name: Install packages
    apt:
      update_cache: yes
      state: present
      name:
      - apt-transport-https
      - dotnet-sdk-3.1
      - aspnetcore-runtime-3.1
      - dotnet-runtime-3.1